import 'dart:convert';
import 'dart:math';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

/// Symmetric per-session cipher for the local App <-> core IPC socket.
///
/// Each newline-framed message is transmitted as
/// `base64(nonce(12) || ChaCha20-Poly1305 ciphertext || tag(16))`. The 32-byte
/// key is generated by the app and handed to the core out-of-band (via the
/// `FLCLASH_IPC_KEY` environment variable at launch), so it never crosses the
/// socket itself; both directions use the same key. Byte-compatible with the
/// core's `golang.org/x/crypto/chacha20poly1305` framing in `server.go`.
class IpcCipher {
  IpcCipher(this.key);

  final List<int> key;
  static final Chacha20 _aead = Chacha20.poly1305Aead();

  static Uint8List generateKey() => _randomBytes(32);

  Future<String> encodeFrame(String message) async {
    final nonce = _randomBytes(12);
    final box = await _aead.encrypt(
      utf8.encode(message),
      secretKey: SecretKey(key),
      nonce: nonce,
    );
    return base64.encode([...nonce, ...box.cipherText, ...box.mac.bytes]);
  }

  Future<String?> decodeFrame(String line) async {
    final trimmed = line.trim();
    if (trimmed.isEmpty) {
      return null;
    }
    Uint8List raw;
    try {
      raw = base64.decode(trimmed);
    } catch (_) {
      return null;
    }
    if (raw.length < 12 + 16) {
      return null;
    }
    try {
      final clear = await _aead.decrypt(
        SecretBox(
          raw.sublist(12, raw.length - 16),
          nonce: raw.sublist(0, 12),
          mac: Mac(raw.sublist(raw.length - 16)),
        ),
        secretKey: SecretKey(key),
      );
      return utf8.decode(clear);
    } catch (_) {
      return null;
    }
  }

  static Uint8List _randomBytes(int length) {
    final random = Random.secure();
    return Uint8List.fromList(
      List<int>.generate(length, (_) => random.nextInt(256)),
    );
  }
}
