// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Run the profile transform on a Rust worker with a fresh, bounded JS runtime.
/// Return logs even when evaluation fails, so the script editor can show them.
Future<ScriptEvaluation> evaluateScript({
  required String script,
  required String config,
}) => RustLib.instance.api.crateApiScriptEvaluateScript(
  script: script,
  config: config,
);

class ScriptEvaluation {
  final String? config;
  final String? error;
  final List<ScriptLog> logs;

  const ScriptEvaluation({this.config, this.error, required this.logs});

  @override
  int get hashCode => config.hashCode ^ error.hashCode ^ logs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptEvaluation &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          error == other.error &&
          logs == other.logs;
}

class ScriptLog {
  final String level;
  final String output;

  const ScriptLog({required this.level, required this.output});

  @override
  int get hashCode => level.hashCode ^ output.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptLog &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          output == other.output;
}
